# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ExocTBlid
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a test to figure
  out github pages for the purpose
  of potentially having a blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ethanblomquist.com" # the base hostname & protocol for your site
twitter_username: ethanblomquist
github_username:  exoctblid

# Build settings
markdown: kramdown
